// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "./interfaces/IPoseidon.sol";

/**
 * @dev Production-ready Poseidon hash interface for 2 inputs.
 * The actual implementation is deployed via bytecode in the deployment script.
 */
contract Poseidon is IPoseidon {
    /**
     * @notice Placeholder function. In a real deployment, this contract address
     * will contain the optimized Poseidon bytecode generated by circomlibjs.
     */
    function poseidon(
        uint256[2] memory /*inputs*/
    ) public view virtual override returns (uint256) {
        revert("Use the deployed bytecode contract");
    }
}
